const watchListItemsTypes = {
    TOGGLE_WATCH_LIST: 'TOGGLE_WATCH_LIST',
    ADD_MOVIE_TO_WATCH_LIST: 'ADD_MOVIE_TO_WATCH_LIST',
    REMOVE_MOVIE_FROM_WATCH_LIST: 'REMOVE_MOVIE_FROM_WATCH_LIST',
    TOTAL_NUMBER_OF_MOVIES: 'TOTAL_NUMBER_OF_MOVIES'
}
export default watchListItemsTypes;